name: pytest summary
description: run tests using pytest and display a summary
author: dariocurr

branding:
  icon: check-square
  color: gray-dark

inputs:
  extensions:
    description: the pytest extensions to install along pytest
    required: false
  options:
    description: the pytest options
    required: false
  output:
    description: the path to the output file to create
    required: false
  paths:
    description: the path to the folder containing the tests
    required: false
    default: tests
  show:
    description: which tests have to be shown in the summary
    required: false

runs:
  using: composite
  steps:
    - if: ${{ !inputs.extensions }}
      run: pip install pytest ${{ inputs.extensions }}
      shell: bash

    - run: pytest ${{ inputs.options }} --junit-xml=.test_report.xml ${{ inputs.paths }}
      shell: bash

    - uses: test-summary/action@v2.4
      if: always()
      with:
        paths: .test_report.xml
        output: ${{ inputs.output }}
        show: ${{ inputs.show }}
