name: Pytest summary
description: Run tests using pytest and display summary
author: Dario Curreri

branding:
  icon: check-square
  color: gray-dark

inputs:
  extensions:
    description: The pytest extensions to install along pytest
    required: false
  options:
    description: The pytest options
    required: false
  output:
    description: The path to the output file to create
    required: false
  paths:
    description: The path to the folder containing the tests
    required: false
    default: tests
  show:
    description: Which tests have to be shown in the summary
    required: false

runs:
  using: composite
  steps:

    - run: pip install pytest ${{ inputs.extensions }}
      shell: bash

    - run: pytest ${{ inputs.options }} --junit-xml=.test_report.xml ${{ inputs.paths }}
      shell: bash

    - uses: test-summary/action@v2.3
      with:
        paths: .test_report.xml
        output: ${{ inputs.output }}
        show: ${{ inputs.show }}
      if: always()
