name: release

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  release:
    uses: dariocurr/.github/.github/workflows/tracking_release.yml@main
    secrets: inherit
    with:
      action_to_track: test-summary/action
