name: validate

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  validate:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: set up python
        uses: actions/setup-python@main
        with:
          python-version: "3.12"

      - name: run tests
        uses: dariocurr/pytest-summary@main
        with:
          extensions: pytest-asyncio
          options: -x
          paths: tests/test_true.py
          show: all
